languageCode = "en"
languageName = "English"
weight = 1
title = "Attack the SOC"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  twitter_cards = true
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "Dylan Tenebruso"
   image = "img/dylan.jpg"
   headline = "Defend, Detect, Respond: Exploring Azure Security and more.."
   bio = "Infosec engineer with a focus in azure security, detection engineering and threat hunting"
   links = [
     { email = "mailto:info@attackthesoc.com" },
     { github = "https://github.com/attackthesoc" },
     { linkedin = "https://www.linkedin.com/in/dylten6/" },
     { bluesky = "https://bsky.app/profile/dylaninfosec.bsky.social" }
   ]