# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "AboutMe()"
  pageRef = "about.md"
  weight = 20

[[main]]
 name = "Community"
 weight = 30

[[main]]
  name = "KQL Search"
  parent = "Community"
  url = "https://kqlsearch.com"

[[main]]
  name = "Michalis Michalos"
  parent = "Community"
  url = "https://www.michalos.net/"

[[main]]
  name = "Bert-Jan Pals"
  parent = "Community"
  url = "https://kqlquery.com/"

[[main]]
  name = "Fabian Bader"
  parent = "Community"
  url = "https://cloudbrothers.info/en/"

[[main]]
  name = "Ru Campbell"
  parent = "Community"
  url = "https://campbell.scot/"

[[main]]
  name = "Alex Verboon"
  parent = "Community"
  url = "https://www.verboon.info/"

[[main]]
  name = "Ugur Koc"
  parent = "Community"
  url = "https://ugurkoc.de/"

[[main]]
  name = "SecurityAura"
  parent = "Community"
  url = "https://medium.com/@securityaura"

[[main]]
  name = "Nathan McNulty"
  parent = "Community"
  url = "https://nathanmcnulty.com/"

[[main]]
  name = "Kusto Insights"
  parent = "Community"
  url = "https://kustoinsights.substack.com/"

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
